# Generated by Django 2.1.7 on 2020-02-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('evaluation', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Avaliação')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('picture', models.ImageField(default='img/products/default', upload_to='img/products/', verbose_name='Foto')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lastUpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
