# Generated by Django 2.1.7 on 2020-02-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(max_length=60, verbose_name='Avaliador')),
                ('comment', models.TextField(max_length=200, verbose_name='Comentário')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lastUpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['lastUpdatedDate'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(max_length=60, verbose_name='Avaliador')),
                ('evaluation', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Avaliação')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['creationDate'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('picture_url', models.CharField(default='https://i.imgur.com/9lEWQF2.jpg', max_length=300, verbose_name='Url da imagem')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desconto')),
                ('onSale', models.BooleanField(default=False, verbose_name='Em promoção')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lastUpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Id do Produto'),
        ),
        migrations.AddField(
            model_name='comment',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Id do Produto'),
        ),
    ]
