# Generated by Django 2.1.7 on 2020-02-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='evaluator',
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.CharField(default='', max_length=60, verbose_name='Pessoa'),
            preserve_default=False,
        ),
    ]
