# Generated by Django 2.1.7 on 2020-04-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200307_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='productId',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='evaluator',
            new_name='evaluator_name',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='comment',
            field=models.TextField(default='', max_length=200, verbose_name='Comentário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
