# Generated by Django 2.1.7 on 2020-04-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200404_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='onSale',
            field=models.BooleanField(default=False, verbose_name='Em promoção'),
        ),
    ]
