# Generated by Django 2.1.7 on 2020-04-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200405_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='productId',
            new_name='product_id',
        ),
    ]
