# Generated by Django 3.0.4 on 2021-10-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211005_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='sendDate',
            field=models.DateTimeField(auto_now_add=True, default='', verbose_name='Enviado em'),
            preserve_default=False,
        ),
    ]
