# Generated by Django 3.0.4 on 2021-10-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211005_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='sendDate',
        ),
    ]
