# Generated by Django 3.0.4 on 2021-10-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_sendmessage_senddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='sentOn',
        ),
    ]
