# Generated by Django 3.0.4 on 2021-10-06 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_sendmessage_senton'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='sendDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Enviado em'),
            preserve_default=False,
        ),
    ]
